# -*- coding: utf-8 -*-
"""ML_2sem_20240212

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1twVCxbvnGvQMuLT7zCQDuKN-kSbD1621
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
from PIL import Image
import matplotlib.pyplot as plt
import numpy as np

image_path = "/content/cat-meme-explosion.webp"
orig_image = Image.open(image_path)
image = Image.open(image_path).convert('L')
image_array = np.array(image)

#количество входных каналов, количество выходных каналов, kernel_size - размер ядра свертки, stride - шаг свертки, padding - размер
conv_layer = nn.Conv2d(1, 1, kernel_size=3, stride=1, padding=1)
print(conv_layer)
image_tensor = torch.from_numpy(image_array).unsqueeze(0).unsqueeze(0).float()
print(image_tensor)
result_tensor = conv_layer(image_tensor)
print(result_tensor)
result_array = result_tensor.squeeze().detach().numpy()
print(result_array)

plt.figure(figsize=(10, 5))
plt.subplot(1, 2, 1)
plt.imshow(orig_image)
plt.title('Original Image')

plt.subplot(1, 2, 2)
plt.imshow(result_array, cmap='gray')
plt.title('Convolved Image')

plt.show()

